MetaCell/geppetto-scidash

components/TestInstances.js
components/common/griddle/ScidashDateRangeCell.js
components/common/griddle/ScidashFilterCell.js

https://trello.com/c/uwUMWlqn/74-test-instances-view-checklist
https://trello.com/c/omkaSDza/91-score-grid-view-sorting-of-score-needs-to-sort-based-on-hidden-column-sortkey
https://trello.com/c/nMYx5799/94-date-sorting-needs-to-sort-based-on-dates-and-not-text
Added missing icon, changed the way timestamp and score sorting
None

Sorting Issues

---

components/AvgScoreDetails.js
components/ScoreDetails.js
components/common/griddle/ScidashAvgScoreDetailLinkColumn.js
components/common/griddle/ScidashScoreDetailLinkColumn.js

* Scrollable modal, Visual clue for active score
* score and sort key as 2 separate fields one under another

Improvements

---

components/AvgScoreDetails.js
components/ScoreDetails.js
components/TestSuites.js
components/common/griddle/ScidashAvgScoreDetailLinkColumn.js
components/common/griddle/ScidashScoreDetailLinkColumn.js

* Score matrix dialog 20% wider

* Color map inside modals

---

components/AvgScoreDetails.js
components/common/griddle/ScidashAvgScoreDetailLinkColumn.js

Visual clue for selected score

Dialog with percent width

---

components/AvgScoreDetails.js
components/common/griddle/ScidashAvgScoreDetailLinkColumn.js

Reverts MetaCell/geppetto-scidash#91

Revert "Dialog with percent width"

---

common/Helper.js
components/TestInstances.js
components/TestSuites.js
components/common/griddle/ScidashBuildInfoColumn.js
components/common/griddle/ScidashDateRangeCell.js
components/common/griddle/ScidashTimestampColumn.js
styles/scidash.less

* Colored cell fix
* Short string on timestamp
* Tooltip bug on build info was defeated

Colored cell fix, short string on timestamp

---

components/ScoreMatrix.js
components/TestSuites.js
components/common/griddle/ScidashModelDetailLinkColumn.js
components/common/griddle/ScidashSuiteNameLinkColumn.js

https://trello.com/c/TjgSs1YB/124-alternate-suites-view-with-no-grouping-by-model
Fix missed data in matrix, visual improvements and sorting

Alternate suite view

---

components/TestInstances.js
components/TestSuites.js
pages/Header.js
pages/home/Home.js

* URL param for pages
* Fixed invalid timestamp crash

Fixes and Improvements for filters

---

components/AvgScoreDetails.js
components/ScoreMatrix.js
components/TestInstances.js
components/TestSuites.js
styles/scidash.less

tilted-titles fix

---

components/AvgScoreDetails.js
styles/scidash.less

fixing broken tilted titles on avg score details component

---

components/AvgScoreDetails.js
components/ScoreMatrix.js
components/common/griddle/ScidashAvgScoreDetailLinkColumn.js
components/common/griddle/ScidashSuiteNameLinkColumn.js
styles/scidash.less

Tilted titles

---

components/AvgScoreDetails.js
components/ScoreDetails.js
components/ScoreMatrix.js
components/common/griddle/ScidashScoreDetailLinkColumn.js
components/common/griddle/ScidashSuiteNameLinkColumn.js
styles/scidash.less

Styling fixes + some minor bug fixes

style changes and css fixes

---

components/score-matrix/ScoreMatrix.js
shared/ScreenShotHelper.js

Screenshot feature refactoring

---

actions/creators/scheduler.js
actions/scheduler.js
components/scheduling/CustomTable.js
components/scheduling/DDList.js
components/scheduling/DDListContainer.js
components/scheduling/Scheduling.js
components/scheduling/SchedulingContainer.js
reducers/scidash-app.js
reducers/scidash-scheduler.js
services/InitialStateService.js

attach actions to scheduler

---

components/page/header/Header.js
components/page/header/HeaderContainer.js
reducers/scidash-app.js
reducers/scidash-user.js
services/InitialStateService.js
services/api/UserApiService.js
styles/scidash.less

https://trello.com/c/Dw9T0aHp/303-1-auth-logout
https://trello.com/c/uEMCpd8J/304-7-auth-password-recovery
https://trello.com/c/SBkFpSdk/301-5-auth-login-page
https://trello.com/c/qmF9DvCc/302-5-auth-register-page
API for React frontend, new views for Auth process

Feature auth

---

actions/creators/models.js
actions/models.js
components/models/Models.js
components/models/ModelsContainer.js
reducers/scidash-models.js
shared/Config.js
shared/adapter/ModelsGriddleAdapter.js

https://trello.com/c/Qs6hSTgE/311-add-filters-to-models-grid
Models grid now with filters

Add filters to models grid

---

actions/creators/global.js
actions/creators/test-suites.js
actions/creators/tests.js
actions/global.js
actions/header.js
components/test-create/TestCreate.js
components/test-create/TestCreateContainer.js
components/test-form/ParamsForm.js
components/test-form/ParamsFormset.js
components/test-form/TestForm.js
models/BaseModel.js
models/TestClass.js
models/TestInstance.js
reducers/scidash-global.js
services/state/GlobalInitialStateService.js
shared/Config.js
shared/Validator.js

https://trello.com/c/KvkzEmVQ/363-validate-test-instance-creation-on-backend
Frontend events and handlers for global backend errors

Feature test instance validation

---

styles/scidash.less

Fixes CSS that made main page container overlap with login buttons when scrolling up

fixes overlapping container with header buttons

---

styles/scidash.less

revert some css changes

---

components/info-dialog/InfoDialog.js
components/model-form/ModelForm.js
components/models/partial.js
components/scheduling/CompatibilityTable.js
components/scheduling/DDList.js
components/test-form/TestForm.js
components/tests/partial.js

Grid's alignment fixed as per screenshoot.

Scheduling grid alignment

---

components/model-form/ModelForm.js

- Fixed model-form validation for all the fields
- Fixed url source update on user input
- Added github conversion to githubusercontent feature

Fix model url

---

actions/creators/models.js
actions/creators/tests.js
components/model-form/ModelForm.js
components/model-form/ParamsTable.js
components/model-form/partials.js
styles/scidash.less

- toggles colors (red/green) when switched on or off
- toggle's style fixed
- label changed to Watch

Fix toggles style

---

actions/creators/models.js
actions/creators/tests.js
components/model-form/ModelForm.js

- Fixed filters duplicates if the string filtered has more than one occurance per instance.

Fix filter duplicates

---

components/model-details/ModelDetails.js
components/model-form/ModelForm.js
components/scores/Scores.js
components/scores/partials.js
components/test-form/TestForm.js

Fix model details link

---

components/model-form/ModelForm.js
components/test-form/TestForm.js

Chips color fixed

---

components/models/partial.js
components/tests/partial.js

fixed clone wokring even if disabled

---

components/griddle-columns/model-view-details/ModelViewDetails.js

fixing undefined get

---

components/scores/Scores.js

scores type filter fixed
